AWSTemplateFormatVersion: '2010-09-09'
Description: Snapper Go application to take snapshot of volumes.
Resources:
  Snapper:
    Properties:
      CodeUri: s3://vatit-lambdas/snapper-go/ce8a99aa5a3b186ec5514748e9f6f62a
      Description: Takes snapshots of instance volumes.
      Environment:
        Variables:
          OPTION: create
      Events:
        CreateSnapshots:
          Properties:
            Input: "{\n  \"option\": \"create\"\n}\n"
            Schedule: cron(0 2 ? * MON-FRI *)
          Type: Schedule
        DeleteSnapshots:
          Properties:
            Input: "{\n  \"option\": \"delete\"\n}\n"
            Schedule: cron(0 2 ? * MON-FRI *)
          Type: Schedule
      FunctionName: snapper-go
      Handler: main
      Role: arn:aws:iam::197094583576:role/snapper
      Runtime: go1.x
      Timeout: 15
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
