---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Snapper Go application to take snapshot of volumes.

Resources:
  Snapper:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 20
      Handler: main
      Runtime: go1.x
      Events:
        CreateSnapshot:
          Type: Api
          Properties:
            Path: /create
            Method: post
