---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Snapper Go application to take snapshot of volumes.

Resources:
  Snapper:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 15
      Handler: main
      Runtime: go1.x
      FunctionName: snapper-go
      Description: Takes snapshots of instance volumes.
      Role: arn:aws:iam::197094583576:role/snapper
      Environment:
        Variables:
          OPTION: create
      Events:
        CreateSnapshots:
          Type: Schedule
          Properties:
            Schedule: cron(0 2 ? * MON-FRI *)
            Input: |
              {
                "option": "create"
              }
        DeleteSnapshots:
          Type: Schedule
          Properties:
            Schedule: cron(0 2 ? * MON-FRI *)
            Input: |
              {
                "option": "delete"
              }
